SET TERM ^ ;

CREATE OR ALTER TRIGGER ADICIONAR_CURTIDA__LOG_TRIGGER
    ACTIVE
    AFTER INSERT
    POSITION 0
        ON CURTIDAS
AS
BEGIN
    INSERT INTO LOG_ATIVIDADES_USUARIOS (ID_USUARIO, ACAO_REALIZADA) VALUES 
        (NEW.ID_USUARIO, 'curtiu um post');
END^

CREATE OR ALTER TRIGGER REMOVER_CURTIDA_LOG_TRIGGER
    ACTIVE
    AFTER DELETE
    POSITION 0
        ON CURTIDAS
AS
BEGIN
    INSERT INTO LOG_ATIVIDADES_USUARIOS (ID_USUARIO, ACAO_REALIZADA) VALUES 
        (OLD.ID_USUARIO, 'removeu sua curtida');
END^

SET TERM ; ^