SET TERM ^ ;

CREATE OR ALTER TRIGGER PERFIL_LOG_TRIGGER
 ACTIVE 
 AFTER UPDATE
 POSITION 0 
  ON USUARIOS
AS 
BEGIN 
    INSERT INTO LOG_ATIVIDADES_USUARIOS (ID_USUARIO, ACAO_REALIZADA) VALUES 
        (NEW.ID, 'atualizou seu perfil');
END^

SET TERM ; ^
