SET TERM ^ ;

CREATE OR ALTER TRIGGER COMENTAR_LOG_TRIGGER
    ACTIVE
    BEFORE INSERT
    POSITION 0
        ON COMENTARIOS
AS
BEGIN
    INSERT INTO LOG_ATIVIDADES_USUARIOS (ID_USUARIO, ACAO_REALIZADA) VALUES 
        (NEW.ID_USUARIO, 'criou um novo comentario');
END^

CREATE OR ALTER TRIGGER REMOVER_COMENTARIO_LOG_TRIGGER
    ACTIVE
    BEFORE DELETE
    POSITION 0
        ON COMENTARIOS
AS
BEGIN
    INSERT INTO LOG_ATIVIDADES_USUARIOS (ID_USUARIO, ACAO_REALIZADA) VALUES 
        (NEW.ID_USUARIO, 'removeu seu comentario');
END^

SET TERM ; ^