SET TERM ^ ;

CREATE OR ALTER TRIGGER ATUALIZAR_CONFIGURACOES_LOG_TRIGGER
    ACTIVE
    BEFORE INSERT
    POSITION 0
        ON CONFIGURACAO_USUARIOS
AS
BEGIN
    INSERT INTO LOG_ATIVIDADES_USUARIOS (ID_USUARIO, ACAO_REALIZADA) VALUES 
        (NEW.ID_USUARIO, 'atualizou suas configuracoes');
END^

SET TERM ; ^