SET TERM ^ ;

CREATE TRIGGER PERFIL_LOG_TRIGGER
 ACTIVE 
 BEFORE UPDATE
 POSITION 0 
  ON USUARIOS
AS 
BEGIN 
    INSERT INTO LOG_ATIVIDADES_USUARIOS (ID_USUARIO, ACAO_REALIZADA) VALUES 
        (NEW.ID, 'updated profile');
END^

SET TERM ; ^
