SET TERM ^ ;

CREATE OR ALTER TRIGGER CRIAR_POST_LOG_TRIGGER 
 ACTIVE 
 BEFORE INSERT
 POSITION 0 
  ON POSTAGENS
AS 
BEGIN 
    INSERT INTO LOG_ATIVIDADES_USUARIOS (ID_USUARIO, ACAO_REALIZADA) VALUES
        (NEW.ID_USUARIO, 'post created');
END^

CREATE OR ALTER TRIGGER ATUALIZAR_POST_LOG_TRIGGER 
 ACTIVE 
 BEFORE UPDATE
 POSITION 0 
  ON POSTAGENS
AS 
BEGIN 
    INSERT INTO LOG_ATIVIDADES_USUARIOS (ID_USUARIO, ACAO_REALIZADA) VALUES
        (NEW.ID_USUARIO, 'post updated');
END^

CREATE OR ALTER TRIGGER DELETAR_POST_LOG_TRIGGER
 ACTIVE
 BEFORE DELETE
 POSITION 0
  ON POSTAGENS
AS
BEGIN
    INSERT INTO LOG_ATIVIDADES_USUARIOS (ID_USUARIO, ACAO_REALIZADA) VALUES
        (OLD.ID_USUARIO, 'post deleted');
END^

SET TERM ; ^
