SET TERM ^ ;

CREATE OR ALTER TRIGGER SEGUIDOR_TRIGGER
 ACTIVE 
 BEFORE INSERT
 POSITION 0
  ON SEGUIDORES
AS 
BEGIN 
    IF (NEW.ID_USUARIO = NEW.ID_SEGUIDOR) THEN
        EXCEPTION SEGUIDOR_EXCEPTION;
END^

SET TERM ; ^
