SET TERM ^ ;

CREATE OR ALTER TRIGGER SEGUIR_USUARIO_TRIGGER
 ACTIVE 
 BEFORE INSERT
 POSITION 0
  ON SEGUIDORES
AS 
BEGIN 
    IF (NEW.ID_USUARIO = NEW.ID_SEGUIDOR) THEN
      EXCEPTION SEGUIDOR_EXCEPTION;
    
    INSERT INTO LOG_ATIVIDADES_USUARIOS (ID_USUARIO, ACAO_REALIZADA) VALUES
      (NEW.ID_USUARIO, 'seguiu um usuario');
END^

CREATE OR ALTER TRIGGER REMOVER_SEGUIDOR_TRIGGER
  ACTIVE
  BEFORE DELETE
  POSITION 0
    ON SEGUIDORES
AS
BEGIN
  INSERT INTO LOG_ATIVIDADES_USUARIOS (ID_USUARIO, ACAO_REALIZADA) VALUES
    (OLD.ID_USUARIO, 'parou de seguir um usuario');
END^

SET TERM ; ^
