DROP TABLE POST_LIKE;
DROP TABLE POST_COMMENT;
DROP TABLE POST;
DROP TABLE USER_FOLLOWER;
DROP TABLE USER_ACTIVITY_LOG;
DROP TABLE USER_SETTINGS;
DROP TABLE USER_ACCOUNT;

DELETE FROM POST_LIKE;
DELETE FROM POST_COMMENT;
DELETE FROM POST;
DELETE FROM USER_FOLLOWER;
DELETE FROM USER_ACTIVITY_LOG;
DELETE FROM USER_SETTINGS;
DELETE FROM USER_ACCOUNT;