SELECT
    U1.nome,
    COUNT(U2.nome) AS TOTAL_DE_SEGUIDORES
FROM
    SEGUIDORES AS S
INNER JOIN USUARIOS AS U1
    ON S.id_usuario = U1.id 
INNER JOIN USUARIOS AS U2
    ON S.id_seguidor = U2.id
GROUP BY U1.nome
ORDER BY TOTAL_DE_SEGUIDORES DESC;