SELECT
    U1.username,
    COUNT(U2.username) AS TOTAL_FOLLOWERS
FROM
    USER_FOLLOWER AS F
INNER JOIN USER_ACCOUNT AS U1
    ON F.user_id = U1.id 
INNER JOIN USER_ACCOUNT AS U2
    ON F.follower_id = U2.id
GROUP BY U1.username
ORDER BY TOTAL_FOLLOWERS DESC;