-- https://stackoverflow.com/questions/34553826/easiest-way-to-create-an-auto-increment-field-in-firebird-database

CREATE TABLE usuarios (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    hash_senha VARBINARY(64) NOT NULL,
    descricao VARCHAR(100),
    genero VARCHAR(25) DEFAULT NULL,
	caminho_foto_perfil VARCHAR(500) DEFAULT '/profile/pic/path',
    data_aniversario DATE DEFAULT NULL,
	verificado BOOLEAN DEFAULT FALSE,
    data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    PRIMARY KEY (id)
);

CREATE TABLE postagens (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_usuario INTEGER,
    conteudo VARCHAR(500) NOT NULL,
    data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    PRIMARY KEY (id),
    FOREIGN KEY (id_usuario) REFERENCES USUARIOS(id) ON DELETE CASCADE
);

CREATE TABLE comentarios (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_usuario INTEGER,
    id_postagem INTEGER,
    conteudo VARCHAR(500) NOT NULL,
    data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    PRIMARY KEY (id),
    FOREIGN KEY (id_usuario) REFERENCES USUARIOS(id) ON DELETE CASCADE,
    FOREIGN KEY (id_postagem) REFERENCES POSTAGENS(id) ON DELETE CASCADE
);

CREATE TABLE curtidas (
    id_usuario INTEGER,
    id_postagem INTEGER,
    
    PRIMARY KEY (id_usuario, id_postagem),
    FOREIGN KEY (id_usuario) REFERENCES USUARIOS(id) ON DELETE CASCADE,
    FOREIGN KEY (id_postagem) REFERENCES POSTAGENS(id) ON DELETE CASCADE
);

CREATE TABLE seguidores (
    id_usuario INTEGER,
    id_seguidor INTEGER,
    
    PRIMARY KEY (id_usuario, id_seguidor),
    FOREIGN KEY (id_usuario) REFERENCES USUARIOS(id) ON DELETE CASCADE,
    FOREIGN KEY (id_seguidor) REFERENCES USUARIOS(id) ON DELETE CASCADE
);

CREATE TABLE log_atividades_usuarios (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_usuario INTEGER,
    
    acao_realizada VARCHAR(128),
    data_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    PRIMARY KEY (id),
    FOREIGN KEY (id_usuario) REFERENCES USUARIOS(id) ON DELETE CASCADE
);

CREATE TABLE configuracao_usuarios (
    id_usuario INTEGER,
    
    perfil_privado BOOLEAN DEFAULT FALSE,
    modo_escuro BOOLEAN DEFAULT FALSE,
    notificacoes BOOLEAN DEFAULT TRUE,
    mostrar_status_online BOOLEAN DEFAULT TRUE,
    permitir_novos_seguidores BOOLEAN DEFAULT TRUE,
	permitir_mensagens_privadas BOOLEAN DEFAULT TRUE,
    filtro_conteudo BOOLEAN DEFAULT TRUE,
    idioma VARCHAR(15) DEFAULT 'pt-BR',
    
    PRIMARY KEY (id_usuario),
    FOREIGN KEY (id_usuario) REFERENCES USUARIOS(id)
);